### ISSUE TITLE
Update config.yaml format for maximum flexibility

### ISSUE THREAD

**Issue by gaurav** [andrewxhill/MOL#114]
As per John's suggestion on September 1st, 2011, we'd like to move to a more complex format for `config.yaml`, so that we have as much flexibility as possible in this file going forward. His proposed format is as follows:

```
collection:
    required:
        fieldname: source
            default: Jetz Lab   # Always at the collection level
            column: SOURCE      # Always at the layer level

    optional:
        fieldname: scientificname
            default: Puma concolor
            column: LATIN
```

(from the "Map of Life - Meeting Notes" shared Google doc)

I'll be working on defining the schema for this new format in the next few days, and then - once we have a format spec everybody's happy with - I'll work on implementing it.
